import logging
import requests
from flask import current_app

logger = logging.getLogger(__name__)

GEMINI_BASE_URL = "https://generativelanguage.googleapis.com/v1beta"

TARA_SYSTEM_INSTRUCTION = """
You are TARA (तारा), a warm, empathetic, and caring AI voice companion and assistant for Indian citizens on the SETU platform.
The user can talk to you about ANYTHING: daily life, friendly conversation, municipal problems (roads, water, electricity, sanitation), or general questions.
Your job is to talk warmly, greet them with 'नमस्ते' when appropriate, listen attentively, and help them with whatever they ask.

Conversation Rules for Spoken Voice:
1. LANGUAGE MIRRORING:
   - Always respond in the EXACT same language and dialect the user spoke in (Hindi, Hinglish, English, Bengali, Tamil, Telugu, Marathi, etc.).
   - Sound like a polite, caring Indian friend or sister over a phone call.
2. SPOKEN BREVITY:
   - NEVER use markdown, asterisks (*), hashtags (#), bullet points, or emojis.
   - Keep responses strictly to 1 or 2 short, natural spoken sentences for fast and snappy voice conversation.
3. WARMTH & CARE:
   - Always be polite, respectful, and genuinely helpful.
"""

class GeminiService:
    @staticmethod
    def _get_api_key_and_model():
        key = current_app.config.get("GEMINI_API_KEY")
        model = current_app.config.get("GEMINI_MODEL", "gemini-3.5-flash-lite")
        if not key:
            raise ValueError("GEMINI_API_KEY is not configured.")
        return key, model

    @classmethod
    def generate_chat_response(cls, messages: list) -> str:
        """
        Sends conversation history to Gemini 3.5 Flash Lite and gets TARA's response.
        messages format:
        [
          {"role": "user", "parts": [{"text": "..."}]},
          {"role": "model", "parts": [{"text": "..."}]}
        ]
        """
        api_key, model = cls._get_api_key_and_model()
        url = f"{GEMINI_BASE_URL}/models/{model}:generateContent?key={api_key}"
        headers = {
            "Content-Type": "application/json"
        }

        payload = {
            "system_instruction": {
                "parts": [
                    {"text": TARA_SYSTEM_INSTRUCTION}
                ]
            },
            "contents": messages,
            "generationConfig": {
                "temperature": 0.5,
                "maxOutputTokens": 40,
                "topP": 0.95
            }
        }

        try:
            response = requests.post(url, headers=headers, json=payload, timeout=20)
            if response.status_code != 200:
                logger.error(f"Gemini API failed ({response.status_code}): {response.text}")
                response.raise_for_status()

            res_json = response.json()
            candidates = res_json.get("candidates", [])
            if not candidates:
                raise ValueError("No response generated by Gemini.")

            content = candidates[0].get("content", {})
            parts = content.get("parts", [])
            if not parts:
                raise ValueError("Empty candidate parts from Gemini.")

            reply_text = parts[0].get("text", "").strip()
            # Clean any stray formatting
            reply_text = reply_text.replace("*", "").replace("#", "").strip()
            logger.info(f"Gemini generated response: {reply_text}")
            return reply_text
        except Exception as e:
            logger.exception("Error during Gemini response generation")
            raise

    @classmethod
    def generate_issue_description(cls, transcript: str, images: list = None, location_info: dict = None, reporter_type: str = None, group_name: str = None) -> dict:
        """
        Synthesizes citizen notes, voice transcripts, attached image evidence, and location details
        into a formal civic grievance with title, description, category (1 of 17), severity,
        people impacted estimate, reporter type, and group attribution.
        """
        api_key, model = cls._get_api_key_and_model()
        url = f"{GEMINI_BASE_URL}/models/{model}:generateContent?key={api_key}"
        headers = {
            "Content-Type": "application/json"
        }

        official_categories_str = ", ".join([
            "'Education'",
            "'Healthcare'",
            "'Agriculture'",
            "'Water Resources'",
            "'Environment'",
            "'Energy'",
            "'Urban Development and Infrastructure'",
            "'Accessibility and Inclusion'",
            "'Public Administration and Governance'",
            "'Rural Livelihoods and Development'",
            "'Disaster Management'",
            "'Transportation and Mobility'",
            "'Sanitation and Waste Management'",
            "'Employment and Entrepreneurship'",
            "'Housing and Community'",
            "'Public Safety and Security'",
            "'Cyber Security'"
        ])

        system_prompt = (
            "You are TARA, the AI Civic Intelligence Engine for SETU (India National Citizen Grievance & Innovation Ecosystem). "
            "A citizen, grassroots collective, civil society organization, or community group has provided a grievance statement, "
            "audio/video transcript, location details, and photographic evidence. "
            "Your task is to synthesize this input into a formal, clear, actionable, and high-impact civic report. "
            "Output strictly valid JSON with no markdown wrapping, containing the following keys: "
            "'title' (concise, formal, max 10 words), "
            "'description' (2-4 sentences explaining what the issue is, specific hazard/impact, and urgency), "
            f"'category' (MUST be exactly one of the 17 official categories: {official_categories_str}), "
            "'severity' (one of: 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'), "
            "'impact_count' (string estimate of people impacted, e.g. '150-300 residents' or '500+ daily commuters'), "
            "'impact_description' (1-2 sentences on who is affected and how), "
            "'reporter_type' (preserve or refine the reporting entity type, e.g. 'Individual Citizen', 'Resident Welfare Association (RWA)', 'Self-Help Group (SHG / Sakhi Mandal)', 'Non-Governmental Organization (NGO / CSO)', 'Gram Sabha / Village Committee', 'Youth Club / Nehru Yuva Kendra', 'Farmers Producer Organization (FPO)', 'ASHA / Anganwadi Frontline Worker', 'Traders / Market Association', or other community body)."
        )

        user_content_parts = []
        
        # Add textual information
        text_context = f"Reported statement/transcript: \"{transcript}\"\n"
        if location_info:
            text_context += (
                f"Location details: Village/Town/City: {location_info.get('villageCity') or location_info.get('village_city') or 'N/A'}, "
                f"Sub-district: {location_info.get('subdistrict') or 'N/A'}, "
                f"District: {location_info.get('district') or 'N/A'}, "
                f"State: {location_info.get('state') or 'N/A'}, "
                f"Pin Code: {location_info.get('pincode') or 'N/A'}\n"
            )
        if reporter_type:
            text_context += f"Reported by type: {reporter_type}\n"
        if group_name:
            text_context += f"Organization/Group name: {group_name}\n"

        user_content_parts.append({"text": text_context})

        # Add image parts if provided (base64 inlineData)
        if images and isinstance(images, list):
            for img in images[:3]: # up to 3 images
                if isinstance(img, dict) and "data" in img:
                    user_content_parts.append({
                        "inlineData": {
                            "mimeType": img.get("mimeType", "image/jpeg"),
                            "data": img["data"]
                        }
                    })
                elif isinstance(img, str) and img.startswith("data:"):
                    try:
                        header, b64_data = img.split(",", 1)
                        mime = header.split(";")[0].replace("data:", "")
                        user_content_parts.append({
                            "inlineData": {
                                "mimeType": mime or "image/jpeg",
                                "data": b64_data
                            }
                        })
                    except Exception:
                        pass

        payload = {
            "system_instruction": {
                "parts": [{"text": system_prompt}]
            },
            "contents": [
                {"role": "user", "parts": user_content_parts}
            ],
            "generationConfig": {
                "temperature": 0.2,
                "maxOutputTokens": 450,
                "responseMimeType": "application/json"
            }
        }

        try:
            response = requests.post(url, headers=headers, json=payload, timeout=25)
            if response.status_code == 200:
                res_json = response.json()
                candidates = res_json.get("candidates", [])
                if candidates:
                    parts = candidates[0].get("content", {}).get("parts", [])
                    if parts:
                        raw_text = parts[0].get("text", "").strip()
                        import json
                        try:
                            clean_text = raw_text.replace("```json", "").replace("```", "").strip()
                            parsed = json.loads(clean_text)
                            return {
                                "title": parsed.get("title", "Civic Grievance Report"),
                                "description": parsed.get("description", transcript),
                                "category": parsed.get("category", "Urban Development and Infrastructure"),
                                "severity": parsed.get("severity", "MEDIUM"),
                                "impact_count": parsed.get("impact_count", "100-250 local residents"),
                                "impact_description": parsed.get("impact_description", "Affects daily commuters and nearby residents."),
                                "reporter_type": parsed.get("reporter_type", reporter_type or "Individual Citizen")
                            }
                        except Exception:
                            logger.warning(f"Could not parse Gemini JSON: {raw_text}")
            logger.warning(f"Gemini generate_issue_description non-200 status {response.status_code}: {response.text}")
        except Exception as e:
            logger.exception("Error in generate_issue_description")

        # NLP Fallback using 17 categories classifier
        from app.ai.classifier import classify_problem
        classified = classify_problem(transcript)
        fallback_title = transcript[:50] + "..." if len(transcript) > 50 else transcript

        return {
            "title": fallback_title or "Civic Grievance Report",
            "description": transcript,
            "category": classified.get("category", "Urban Development and Infrastructure"),
            "severity": "MEDIUM",
            "impact_count": "50-150 residents",
            "impact_description": "Local residents facing disruption in civic amenities.",
            "reporter_type": reporter_type or "Individual Citizen"
        }


