import logging
import requests
from flask import current_app

logger = logging.getLogger(__name__)

GEMINI_BASE_URL = "https://generativelanguage.googleapis.com/v1beta"

TARA_SYSTEM_INSTRUCTION = """
You are TARA (तारा), an empathetic, polite, and dedicated voice assistant for SETU - the Indian National Citizen Grievance and Problem Reporting platform.
Your primary role is to listen to citizens—especially elderly and rural citizens—who are reporting public issues (such as broken roads, potholes, water supply problems, garbage accumulation, broken streetlights, or sewage overflow).

Follow these vital conversation principles:
1. LANGUAGE MIRRORING:
   - Always respond in the EXACT same language and dialect the citizen spoke in.
   - If the citizen speaks in Hindi, respond in natural, warm, polite spoken Hindi.
   - If the citizen speaks in English, respond in courteous, simple Indian English.
   - If the citizen speaks in Hinglish or mixed languages, respond in natural conversational Hinglish.
   - If the citizen speaks in another regional Indian language (Bengali, Marathi, Tamil, Telugu, Gujarati, etc.), respond in that language.

2. ACTIVE REFLECTIVE LISTENING:
   - Always validate and acknowledge the citizen's grievance first (e.g., "जी, मैं समझ गई, सड़क पर बड़े गड्ढों की वजह से परेशानी हो रही है।" or "I understand, waterlogging and damaged roads are causing serious inconvenience.").
   - Show genuine empathy and respect. Treat elderly citizens with highest regard.

3. CONCISE SPOKEN CONVERSATION:
   - Your responses will be read aloud by voice synthesis over the phone speaker.
   - NEVER use markdown formatting, bullet points, asterisks (*), hashtags (#), or emojis.
   - Keep your responses to 1 to 3 short, clear, natural spoken sentences.
   - Ask only ONE follow-up question at a time (for example, the exact location, landmark, or how long the issue has persisted).

4. PATIENCE & WARMTH:
   - Never sound hurried, bureaucratic, or robotic.
   - Be like a helpful, caring community support officer.
"""

class GeminiService:
    @staticmethod
    def _get_api_key_and_model():
        key = current_app.config.get("GEMINI_API_KEY")
        model = current_app.config.get("GEMINI_MODEL", "gemini-3.5-flash-lite")
        if not key:
            raise ValueError("GEMINI_API_KEY is not configured.")
        return key, model

    @classmethod
    def generate_chat_response(cls, messages: list) -> str:
        """
        Sends conversation history to Gemini 3.5 Flash Lite and gets TARA's response.
        messages format:
        [
          {"role": "user", "parts": [{"text": "..."}]},
          {"role": "model", "parts": [{"text": "..."}]}
        ]
        """
        api_key, model = cls._get_api_key_and_model()
        url = f"{GEMINI_BASE_URL}/models/{model}:generateContent?key={api_key}"
        headers = {
            "Content-Type": "application/json"
        }

        payload = {
            "system_instruction": {
                "parts": [
                    {"text": TARA_SYSTEM_INSTRUCTION}
                ]
            },
            "contents": messages,
            "generationConfig": {
                "temperature": 0.6,
                "maxOutputTokens": 300,
                "topP": 0.95
            }
        }

        try:
            response = requests.post(url, headers=headers, json=payload, timeout=20)
            if response.status_code != 200:
                logger.error(f"Gemini API failed ({response.status_code}): {response.text}")
                response.raise_for_status()

            res_json = response.json()
            candidates = res_json.get("candidates", [])
            if not candidates:
                raise ValueError("No response generated by Gemini.")

            content = candidates[0].get("content", {})
            parts = content.get("parts", [])
            if not parts:
                raise ValueError("Empty candidate parts from Gemini.")

            reply_text = parts[0].get("text", "").strip()
            # Clean any stray formatting
            reply_text = reply_text.replace("*", "").replace("#", "").strip()
            logger.info(f"Gemini generated response: {reply_text}")
            return reply_text
        except Exception as e:
            logger.exception("Error during Gemini response generation")
            raise
