import logging
import requests
from flask import current_app

logger = logging.getLogger(__name__)

GEMINI_BASE_URL = "https://generativelanguage.googleapis.com/v1beta"

TARA_SYSTEM_INSTRUCTION = """
You are TARA (तारा), a warm, empathetic, and caring AI voice companion and assistant for Indian citizens on the SETU platform.
The user can talk to you about ANYTHING: daily life, friendly conversation, municipal problems (roads, water, electricity, sanitation), or general questions.
Your job is to talk warmly, greet them with 'नमस्ते' when appropriate, listen attentively, and help them with whatever they ask.

Conversation Rules for Spoken Voice:
1. LANGUAGE MIRRORING:
   - Always respond in the EXACT same language and dialect the user spoke in (Hindi, Hinglish, English, Bengali, Tamil, Telugu, Marathi, etc.).
   - Sound like a polite, caring Indian friend or sister over a phone call.
2. SPOKEN BREVITY:
   - NEVER use markdown, asterisks (*), hashtags (#), bullet points, or emojis.
   - Keep responses strictly to 1 or 2 short, natural spoken sentences for fast and snappy voice conversation.
3. WARMTH & CARE:
   - Always be polite, respectful, and genuinely helpful.
"""

class GeminiService:
    @staticmethod
    def _get_api_key_and_model():
        key = current_app.config.get("GEMINI_API_KEY")
        model = current_app.config.get("GEMINI_MODEL", "gemini-3.5-flash-lite")
        if not key:
            raise ValueError("GEMINI_API_KEY is not configured.")
        return key, model

    @classmethod
    def generate_chat_response(cls, messages: list) -> str:
        """
        Sends conversation history to Gemini 3.5 Flash Lite and gets TARA's response.
        messages format:
        [
          {"role": "user", "parts": [{"text": "..."}]},
          {"role": "model", "parts": [{"text": "..."}]}
        ]
        """
        api_key, model = cls._get_api_key_and_model()
        url = f"{GEMINI_BASE_URL}/models/{model}:generateContent?key={api_key}"
        headers = {
            "Content-Type": "application/json"
        }

        payload = {
            "system_instruction": {
                "parts": [
                    {"text": TARA_SYSTEM_INSTRUCTION}
                ]
            },
            "contents": messages,
            "generationConfig": {
                "temperature": 0.5,
                "maxOutputTokens": 40,
                "topP": 0.95
            }
        }

        try:
            response = requests.post(url, headers=headers, json=payload, timeout=20)
            if response.status_code != 200:
                logger.error(f"Gemini API failed ({response.status_code}): {response.text}")
                response.raise_for_status()

            res_json = response.json()
            candidates = res_json.get("candidates", [])
            if not candidates:
                raise ValueError("No response generated by Gemini.")

            content = candidates[0].get("content", {})
            parts = content.get("parts", [])
            if not parts:
                raise ValueError("Empty candidate parts from Gemini.")

            reply_text = parts[0].get("text", "").strip()
            # Clean any stray formatting
            reply_text = reply_text.replace("*", "").replace("#", "").strip()
            logger.info(f"Gemini generated response: {reply_text}")
            return reply_text
        except Exception as e:
            logger.exception("Error during Gemini response generation")
            raise

    @classmethod
    def generate_issue_description(cls, transcript: str) -> dict:
        """
        Synthesizes a citizen's spoken voice transcript into a clear, formal civic grievance
        with title, description, category, and severity using Gemini 3.5 Flash Lite.
        """
        api_key, model = cls._get_api_key_and_model()
        url = f"{GEMINI_BASE_URL}/models/{model}:generateContent?key={api_key}"
        headers = {
            "Content-Type": "application/json"
        }

        system_prompt = (
            "You are an AI Civic Intake Assistant for SETU (India National Grievance Portal). "
            "A citizen has provided a spoken report or draft about a public problem in their locality. "
            "Your task is to convert this input into a formal, clear, and actionable civic issue report. "
            "Output strictly valid JSON with no markdown wrapping, no backticks, containing the following keys: "
            "'title' (concise string, max 10 words), "
            "'description' (2-4 sentences explaining what the issue is, the specific hazard/impact, and urgency), "
            "'category' (one of: 'WATER_SANITATION', 'URBAN_INFRASTRUCTURE', 'ENERGY_ELECTRICITY', 'ENVIRONMENT_WASTE', 'HEALTHCARE', 'AGRICULTURE_RURAL'), "
            "'severity' (one of: 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')."
        )

        payload = {
            "system_instruction": {
                "parts": [{"text": system_prompt}]
            },
            "contents": [
                {"role": "user", "parts": [{"text": f"Citizen voice statement: \"{transcript}\""}]}
            ],
            "generationConfig": {
                "temperature": 0.3,
                "maxOutputTokens": 300,
                "responseMimeType": "application/json"
            }
        }

        try:
            response = requests.post(url, headers=headers, json=payload, timeout=20)
            if response.status_code == 200:
                res_json = response.json()
                candidates = res_json.get("candidates", [])
                if candidates:
                    parts = candidates[0].get("content", {}).get("parts", [])
                    if parts:
                        raw_text = parts[0].get("text", "").strip()
                        import json
                        try:
                            clean_text = raw_text.replace("```json", "").replace("```", "").strip()
                            parsed = json.loads(clean_text)
                            return {
                                "title": parsed.get("title", "Civic Grievance Report"),
                                "description": parsed.get("description", transcript),
                                "category": parsed.get("category", "URBAN_INFRASTRUCTURE"),
                                "severity": parsed.get("severity", "MEDIUM")
                            }
                        except Exception:
                            logger.warning(f"Could not parse Gemini JSON: {raw_text}")
            logger.warning(f"Gemini generate_issue_description non-200 status {response.status_code}: {response.text}")
        except Exception as e:
            logger.exception("Error in generate_issue_description")

        # Fallback if Gemini request fails or response cannot be parsed
        fallback_title = transcript[:50] + "..." if len(transcript) > 50 else transcript
        return {
            "title": fallback_title or "Citizen Civic Report",
            "description": transcript,
            "category": "URBAN_INFRASTRUCTURE",
            "severity": "MEDIUM"
        }

